### ISSUE TITLE
About Python Implement for Joystick Control

### ISSUE THREAD

**Issue by CTCingithub** [Rooholla-KhorramBakht/FR3Py#6]
In examples/robot_interface_tutorial.ipynb, there is

```python
from pyJoy.joy_daq import JoyManager
import time
joy1  = JoyManager()
joy1.start_daq(joy_idx=0)
joy1.offset_calibration()
time.sleep(3)
```

`pyJoy` is not mentined in setup.cfg. I'm not able to find `pyJoy`, but found [PyJoy](https://github.com/iamedu/PyJoy) which is no longer maintained.

Please tell me where to install the corresponding Python implement for Joystick control. Thank you in advance for your help.

**Comment by Rooholla-KhorramBakht** [comment]
Thank you for trying out our code base! This is rapidly changing project and that's why we missed adding the dependency into the package. You should be able run the examples now. Just note that our joystick interface class is for Logitech Extreme 3D Pro but you should be able to adapt it to what ever joystick you like.
